<a href="https://colab.research.google.com/github/19PA1A04B6/PYTHON-BASICS/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [12]:
import numpy as np
np.arange(10,30,5)


array([10, 15, 20, 25])

In [47]:
import numpy as np
a=np.arange(15) .reshape(3,5)
a
a.shape
a.ndim
a.dtype
a.itemsize
a.size
type(a)

numpy.ndarray

In [41]:
import numpy as np
np.zeros((3,4))
np.ones((2,3), dtype=np.int16)
np.empty((2,3))
np.eye(3)
np.full ((2,2),7)
a=np.random.random((2,3))
a

array([[0.61848198, 0.44425927, 0.91273376],
       [0.5959455 , 0.89317441, 0.94339563]])

In [50]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)
c=a-b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<35)
a[0] +10
print(a)

[20 30 40 50]
[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]
[20 30 40 50]


In [53]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])
print(a)
print(b)
print(a*b)
print(a.dot(b))
print(np.dot(a,b))
print(a@b)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]
[[2 0]
 [0 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]
[[5 4]
 [3 4]]


In [59]:
b=np.arange(12).reshape(3,4)
print(b)
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))
print(b.min(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]
[0 4 8]


In [61]:
a=np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])